apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-pauwels-labs-main-github-pauwels-labs-homepage
  namespace: pauwels-labs-main
  labels:
    toolkit.fluxcd.io/tenant: pauwels-labs-main
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: tenant-repositories-ssh
    kind: SecretStore
  target:
    name: ssh-pauwels-labs-main-github-pauwels-labs-homepage
    deletionPolicy: "Delete"
    template:
      metadata:
        labels:
          toolkit.fluxcd.io/tenant: pauwels-labs-main
  data:
  - secretKey: identity
    remoteRef:
      key: tenants/pauwels-labs-main/repositories/github/pauwels-labs/homepage/ssh
      property: identity
  - secretKey: identity.pub
    remoteRef:
      key: tenants/pauwels-labs-main/repositories/github/pauwels-labs/homepage/ssh
      property: identity.pub
  - secretKey: known_hosts
    remoteRef:
      key: tenants/pauwels-labs-main/repositories/github/pauwels-labs/homepage/ssh
      property: known_hosts
