apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-${tenantname}-github-pauwels-labs-homepage
  labels:
    toolkit.fluxcd.io/tenant: ${tenantname}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: tenant-repositories-ssh
    kind: SecretStore
  target:
    name: ssh-${tenantname}-github-pauwels-labs-homepage
    deletionPolicy: "Delete"
    template:
      metadata:
        labels:
          toolkit.fluxcd.io/tenant: ${tenantname}
  data:
  - secretKey: identity
    remoteRef:
      key: tenants/${tenantnamespaceprefix}${tenantname}/repositories/github/pauwels-labs/homepage/ssh/cd
      property: identity
  - secretKey: identity.pub
    remoteRef:
      key: tenants/${tenantnamespaceprefix}${tenantname}/repositories/github/pauwels-labs/homepage/ssh/cd
      property: identity.pub
  - secretKey: known_hosts
    remoteRef:
      key: tenants/${tenantnamespaceprefix}${tenantname}/repositories/github/pauwels-labs/homepage/ssh/cd
      property: known_hosts
