apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: github-pauwels-labs-homepage
  namespace: "${tenantnamespaceprefix}pauwels-labs-main"
  labels:
    toolkit.fluxcd.io/tenant: pauwels-labs-main
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: ssh-pauwels-labs-main-github-pauwels-labs-homepage
  url: ssh://git@github.com/pauwels-labs/homepage
