apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: homepage
  namespace: pauwels-labs-main
spec:
  interval: 1m0s
  serviceAccountName: pauwels-labs-main
  targetNamespace: pauwels-labs-main
  sourceRef:
    kind: GitRepository
    name: github-pauwels-labs-homepage
  path: ./deploy
  prune: true
  wait: true
  timeout: 30s
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: external-config-data
